version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      -image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package.jsoon" }}
        key: v1-dependencies-

      - run:
        name: Install dependencies
        command: npm install

      - save_cache:
        paths:
          - node_modules
        key: va1-dependencies-{{ checksum "package.json" }}

      - run:
        name: test
        command: echo "no test"